import { ChakraProvider } from '@chakra-ui/react'
import Head from "next/head";
import { useRouter } from 'next/router';
import { useEffect } from 'react';
import ProgressBar from "@badrap/bar-of-progress";
import "../styles/global.css";

const progress = new ProgressBar({
  size: 1.5,
  color: "#DE1B1B",
  className: "bar-of-progress",
});

function MyApp({ Component, pageProps }) {
  const router = useRouter();

  useEffect(() => {
    router.events.on('routeChangeStart', () => progress.start());
    router.events.on("routeChangeComplete", () => progress.finish());
  }, [router.events]);

  return <ChakraProvider>
    <Head>
      <title>Arhamymr</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Component {...pageProps} />
  </ChakraProvider>
}

export default MyApp
